version: '3'
services:
  # サービス名
  web:
    image: nginx:1.15.6      #インストールするイメージ名
    ports:
        # ポートフォワーディング。
        #ホスト側（自分が使っているパソコン）のポート:コンテナ側のポート
        #ホスト側の8000にアクセスしたらコンテナの80番ポートに転送してくれるので、「localhost:8000」でアクセス可能
      - "80:80"
      # ホスト側（自分が使っているパソコン）にあるディレクトリやファイルをコンテナでも使えるようにする。
      #こうすることで、ホスト側での変更がコンテナへも反映される。（dockerコンテナに入って直接編集する訳ではない）
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  # サービス名
  app:
    build: ./docker/php
    ports:
      - 9000:9000
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
  # サービス名
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: --general-log=true --general-log-file=/dev/stdout
    ports:
      - "3306:3306"
    volumes:
      - temp-mysql-data:/var/lib/mysql
volumes:
  temp-mysql-data:
